### ISSUE TITLE
Write this in Basil?

### ISSUE THREAD

**Issue by dumblob** [elucent/mdtest#1]
Would be interesting to write such small apps in Basil (`.md` files parsing could be simplified by using an existing external C lib) :wink:.

**Comment by dumblob** [comment]
That'd prove Basil's capability to easily deploy Basil itself as well as the resulting app.

**Comment by elucent** [comment]
I think you are really overestimating the stability and functionality of Basil here... 😓 

Even so, `mdtest` will probably always stay written in Python, since to my estimation it's pretty much the most widespread/portable scripting language. Keeps things simple.

**Comment by dumblob** [comment]
> I think you are really overestimating the stability and functionality of Basil here... sweat

Just wanted to encourage you :wink:. OTOH I still think it'd be a nice exercise - one has something to compare to, it's non-trivial yet simple, and it's useful.

> Even so, `mdtest` will probably always stay written in Python, since to my estimation it's pretty much the most widespread/portable scripting language. Keeps things simple.

Yeah, true. I wish Basil could achieve similar support across major platforms at some point.
